"""Added user-quote relationship

Revision ID: 0098be0495be
Revises: 1ea982a8d210
Create Date: 2018-07-16 18:38:24.567292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0098be0495be'
down_revision = '1ea982a8d210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quoterequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('UserQuote', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quoterequests', schema=None) as batch_op:
        batch_op.drop_constraint('UserQuote', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
