"""Test

Revision ID: 1ea982a8d210
Revises: 60d63605faac
Create Date: 2018-07-16 18:35:13.563170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea982a8d210'
down_revision = '60d63605faac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quoterequests', schema=None) as batch_op:
        batch_op.drop_column('user')
        batch_op.drop_column('user_id')
        batch_op.drop_column('userid')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('access_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_level', sa.VARCHAR(length=120), nullable=True))

    with op.batch_alter_table('quoterequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
