"""Changed table names

Revision ID: 2e669bc05698
Revises: 8cfb618cb4d9
Create Date: 2018-07-19 17:38:46.835529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e669bc05698'
down_revision = '8cfb618cb4d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('street', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('zip_code', sa.String(length=120), nullable=True),
    sa.Column('stripe_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_User_email'), ['email'], unique=True)

    op.create_table('QuoteRequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('street', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('time_requested', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('misc', sa.String(length=200), nullable=True),
    sa.Column('stripe_id', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('QuoteRequests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_QuoteRequests_customer'), ['customer'], unique=False)
        batch_op.create_index(batch_op.f('ix_QuoteRequests_email'), ['email'], unique=False)

    op.create_table('JobData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('estimate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['QuoteRequests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('JobNote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('image_name', sa.String(length=500), nullable=True),
    sa.Column('time_submitted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['QuoteRequests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jobdata')
    op.drop_table('jobnotes')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')

    op.drop_table('user')
    with op.batch_alter_table('quoterequests', schema=None) as batch_op:
        batch_op.drop_index('ix_quoterequests_customer')
        batch_op.drop_index('ix_quoterequests_email')

    op.drop_table('quoterequests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quoterequests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('submit_time', sa.DATETIME(), nullable=True),
    sa.Column('street', sa.VARCHAR(length=120), nullable=True),
    sa.Column('city', sa.VARCHAR(length=120), nullable=True),
    sa.Column('state', sa.VARCHAR(length=120), nullable=True),
    sa.Column('zip_code', sa.INTEGER(), nullable=True),
    sa.Column('phone', sa.INTEGER(), nullable=True),
    sa.Column('time_requested', sa.VARCHAR(length=120), nullable=True),
    sa.Column('description', sa.VARCHAR(length=240), nullable=True),
    sa.Column('paid', sa.BOOLEAN(), nullable=True),
    sa.Column('complete', sa.BOOLEAN(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=120), nullable=True),
    sa.Column('stripe_id', sa.VARCHAR(length=120), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('misc', sa.VARCHAR(length=200), nullable=True),
    sa.CheckConstraint('complete IN (0, 1)'),
    sa.CheckConstraint('paid IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quoterequests', schema=None) as batch_op:
        batch_op.create_index('ix_quoterequests_email', ['email'], unique=False)
        batch_op.create_index('ix_quoterequests_customer', ['customer'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('role', sa.INTEGER(), nullable=True),
    sa.Column('confirmed', sa.BOOLEAN(), nullable=True),
    sa.Column('stripe_id', sa.VARCHAR(length=120), nullable=True),
    sa.Column('city', sa.VARCHAR(length=120), nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('state', sa.VARCHAR(length=120), nullable=True),
    sa.Column('street', sa.VARCHAR(length=120), nullable=True),
    sa.Column('zip_code', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('confirmed IN (0, 1)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    op.create_table('jobnotes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quote_id', sa.INTEGER(), nullable=True),
    sa.Column('note', sa.VARCHAR(length=500), nullable=True),
    sa.Column('image_name', sa.VARCHAR(length=500), nullable=True),
    sa.Column('time_submitted', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quoterequests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobdata',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quote_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('estimate', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quoterequests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('JobNote')
    op.drop_table('JobData')
    with op.batch_alter_table('QuoteRequests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_QuoteRequests_email'))
        batch_op.drop_index(batch_op.f('ix_QuoteRequests_customer'))

    op.drop_table('QuoteRequests')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_email'))

    op.drop_table('User')
    # ### end Alembic commands ###
