"""Added fields to user table

Revision ID: 55161649d4d7
Revises: f1d957757eca
Create Date: 2018-07-05 11:06:32.761151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55161649d4d7'
down_revision = 'f1d957757eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('street', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('zip_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'street')
    op.drop_column('user', 'state')
    op.drop_column('user', 'name')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
