"""Fixed quoterequests table

Revision ID: 582290bf5eab
Revises: 9e37bccc7cf8
Create Date: 2018-06-13 20:21:51.686002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582290bf5eab'
down_revision = '9e37bccc7cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quoterequests', sa.Column('status', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quoterequests', 'status')
    # ### end Alembic commands ###
