"""Added jobnotes table

Revision ID: 60d63605faac
Revises: 55161649d4d7
Create Date: 2018-07-15 10:07:16.530410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d63605faac'
down_revision = '55161649d4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobnotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('image_name', sa.String(length=500), nullable=True),
    sa.Column('time_submitted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quoterequests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobnotes')
    # ### end Alembic commands ###
