"""Added miscellanious notes field in QuoteRequests table

Revision ID: 8cfb618cb4d9
Revises: 0098be0495be
Create Date: 2018-07-19 12:33:04.766855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cfb618cb4d9'
down_revision = '0098be0495be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quoterequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('misc', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quoterequests', schema=None) as batch_op:
        batch_op.drop_column('misc')

    # ### end Alembic commands ###
