"""added stripe_id field for payments

Revision ID: 9f40523319b7
Revises: 582290bf5eab
Create Date: 2018-06-19 19:53:28.003357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f40523319b7'
down_revision = '582290bf5eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quoterequests', sa.Column('stripe_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quoterequests', 'stripe_id')
    # ### end Alembic commands ###
